INSERT INTO PARTY VALUES (1, 'HOMER', 'SIMPSON');
INSERT INTO ROLE VALUES (1, 'DONUT EATER');
INSERT INTO ROLE VALUES (2, 'NUCLEAR SAFERTY ENGINEER');
INSERT INTO ORGANIZATION VALUES (1, 'STONE CUTTERS');
INSERT INTO PARTY_ORG_ROLE VALUES (1, 1, 1);