CREATE TABLE PARTY (
	PARTY_ID INT NOT NULL,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE ORGANIZATION (
	ORG_ID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL
);

CREATE TABLE ROLE (
	ROLE_ID INT NOT NULL,
	NAME VARCHAR(40) NOT NULL
);


CREATE TABLE PARTY_ORG_ROLE (
	PARTY_ID INT NOT NULL, 
    ORG_ID INT NOT NULL, 
    ROLE_ID INT NOT NULL
);